// export { default as Home } from './Home';
// export { default as Navbar } from './Navbar';
// export { default as About } from './About';
// export { default as Hero } from './Hero';
// export { default as Project } from './Project';
export { default as Process } from './NewProcess';
// export { default as Footer } from './Footer';
// export { default as Testimonials } from './Testimonials';
// export { default as Menu } from './Side-Menu/SideHome';
// export { default as FrontEnd } from './front-end';
// export { default as Services } from './Services';