import type { Metadata } from "next";
import "./globals.css";

import Navbar from "./component/Navbar/Navbar";
import {ReactLenis} from 'lenis/react'
import Preloader from "./component/Preloader"; // Import the Preloader component
import FollowCursor from "@/components/ui/FollowCursor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 


{
  return (
    <html lang="en">
      <body className="h-screen overflow-y-scroll scrollbar-thin">
        {/* Add the Preloader here */}
        
        <FollowCursor/>
       
        {children}
      
      </body>
    </html>
  );
}
