
import type { Metadata } from "next";

import "./globals.css";

import Navbar from "./component/Navbar";
import { Footer } from "./component/Home/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en" >
    
      <body className="h-screen overflow-y-scroll scrollbar-thin ">
         <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
